# -*- coding: utf-8 -*-
"""Project1_AIforChem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lkc-RPddyy8KjrnaJrgSU8Yg4mdApR_B
"""

import re
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from io import StringIO
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (accuracy_score, precision_score, recall_score, roc_auc_score, roc_curve)

#load file
with open("Experimental-PSORTdb-v4.00.tsv", "r", encoding="latin-1") as file:
    content = file.read()
#gets rid of weird html webpage tags
match = re.search(r"<pre[^>]*>(.*?)</pre>", content, re.DOTALL)
clean_text = match.group(1).strip() if match else content.strip()


df = pd.read_csv(StringIO(clean_text), sep="\t")

#lowercase column names
df.columns = [col.lower() for col in df.columns]


#only keep bacterial proteins
df = df[df["gramstain"].notna() & ~df["gramstain"].str.contains("archaea", case=False, na=False)].copy()


#only keep proteins with experimental localization
df = df[df["experimental_localization"].notna() & ~df["experimental_localization"].str.contains("curated for secondary localization only", case=False, na=False)].copy()


#binarize
df["is_membrane"] = df["experimental_localization"].apply(lambda x: 1 if "membrane" in str(x).lower() else 0)


#retrieve protein sequences from uniprot in batches
def get_uniprot_sequences(accessions, batch_size=100):
    sequences = {}
    total = len(accessions)

    for start in range(0, total, batch_size):
        batch = accessions[start:start + batch_size]

        print(f"getting sequences {start + 1}-{min(start + batch_size, total)} of {total}")

        query = " OR ".join([f"accession:{acc}" for acc in batch])
        url = "https://rest.uniprot.org/uniprotkb/search"
        params = {"query": query, "format": "fasta", "size": batch_size}

        try:
            response = requests.get(url, params=params, timeout=60)
            response.raise_for_status()
        except requests.RequestException as e:
            print("request failed:", e)
            continue

        lines = response.text.strip().splitlines()
        current_accession = None
        current_sequence = []

        for line in lines:
            if line.startswith(">"):
                if current_accession is not None:
                    sequences[current_accession] = "".join(current_sequence)

                parts = line.split("|")

                if len(parts) >= 2:
                    current_accession = parts[1]
                else:
                    current_accession = None

                current_sequence = []

            else:
                current_sequence.append(line.strip())

        if current_accession is not None:
            sequences[current_accession] = "".join(current_sequence)

    return sequences


#get uniprot accessions
accessions = (df["swissprot_id"].dropna().astype(str).str.strip().unique())

sequence_dict = get_uniprot_sequences(accessions, batch_size=100)

#add sequences to dataframe
df["sequence"] = (df["swissprot_id"].astype(str).str.strip().map(sequence_dict))

#remove proteins without sequences
df = df.dropna(subset=["sequence"]).copy()

#define AA groups
hydrophobic = "AVILMFWY"
polar = "STNQ"
positive = "KR"
negative = "DE"
charged = "KRDE"
aromatic = "FWY"

def calculate_features(sequence):
    sequence = str(sequence).upper()
    length = len(sequence)

    if length == 0:
        return None

    features = {}

    #fraction of AA in whole sequence
    amino_acids = "ACDEFGHIKLMNPQRSTVWY"

    for aa in amino_acids:
        features[f"{aa}_fraction"] = sequence.count(aa) / length

    #AA features
    features["hydrophobic_fraction"] = (sum(aa in hydrophobic for aa in sequence) / length)
    features["polar_fraction"] = (sum(aa in polar for aa in sequence) / length)
    features["positive_fraction"] = (sum(aa in positive for aa in sequence) / length)
    features["negative_fraction"] = (sum(aa in negative for aa in sequence) / length)
    features["charged_fraction"] = (sum(aa in charged for aa in sequence) / length)
    features["aromatic_fraction"] = (sum(aa in aromatic for aa in sequence) / length)

    #sequence length
    features["sequence_length"] = length

    return features


#calculate features for every protein
feature_data = df["sequence"].apply(calculate_features)

#convert dictionaries into columns
feature_df = pd.DataFrame(feature_data.tolist(), index=df.index)

#add features to dataframe
df = pd.concat([df, feature_df], axis=1)

#remove rows with no features
df = df.dropna(subset=feature_df.columns).copy()


feature_columns = feature_df.columns.tolist()

X = df[feature_columns]
y = df["is_membrane"]


#split training vs testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)


#pipeline creation
pipeline = Pipeline([
    ("selector", SelectKBest(score_func=f_classif, k=10)),
    ("scaler", StandardScaler()),
    ("classifier", SVC(probability=True, random_state=42))])

#grid search parameters
param_grid = {
    "classifier__C": [0.1, 1, 10],
    "classifier__kernel": ["linear", "rbf"]}

#gridsearchCV
grid = GridSearchCV(pipeline, param_grid, cv=5, scoring="accuracy", n_jobs=-1)

grid.fit(X_train, y_train)

#best model from gridsearchCV
best_model = grid.best_estimator_

print("best parameters:", grid.best_params_)
print("best cross-validation accuracy:", grid.best_score_)

#make predictions
y_train_pred = best_model.predict(X_train)
y_test_pred = best_model.predict(X_test)

#prediction probabilities
y_train_prob = best_model.predict_proba(X_train)[:, 1]
y_test_prob = best_model.predict_proba(X_test)[:, 1]


train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

train_precision = precision_score(y_train, y_train_pred)
test_precision = precision_score(y_test, y_test_pred)

train_recall = recall_score(y_train, y_train_pred)
test_recall = recall_score(y_test, y_test_pred)

train_roc_auc = roc_auc_score(y_train, y_train_prob)
test_roc_auc = roc_auc_score(y_test, y_test_prob)

print("training accuracy:", train_accuracy)
print("testing accuracy:", test_accuracy)

print("training precision:", train_precision)
print("testing precision:", test_precision)

print("training recall:", train_recall)
print("testing recall:", test_recall)

print("training roc auc:", train_roc_auc)
print("testing roc auc:", test_roc_auc)

#identifies selected features
selected_features = X.columns[best_model.named_steps["selector"].get_support()]

print("selected features:")
print(selected_features.tolist())

#calculate roc curves
train_fpr, train_tpr, _ = roc_curve(y_train, y_train_prob)
test_fpr, test_tpr, _ = roc_curve(y_test, y_test_prob)

#create roc curves
plt.figure(figsize=(7, 5))

plt.plot(train_fpr, train_tpr, label=f"Training auc = {train_roc_auc:.3f}")
plt.plot(test_fpr, test_tpr, label=f"Testing auc = {test_roc_auc:.3f}")
plt.plot([0, 1], [0, 1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()